### PR TITLE
fix: validate prefix pattern during router creation

### LINKED ISSUE #53: "named prefix" should be enforced as a prefix, or should work in the middle of a path
Example code:

```lua
local Router = require "radix-router"
local router, err = Router.new({
  {
    paths = { "/Accounts/{*middle}/Messages.json" },
    handler = "1"
  }
})
if not router then
  error("failed to create router: " .. err)
end

assert(nil == router:match("/Accounts/", { method = "POST" }))
assert("1" == router:match("/Accounts/abc/123/Messages.json", { method = "POST" }))
```

This will error on any attempt to match against paths under `/Accounts/`

#### Expected Behavior
I expected either:
1. Both matches run without erroring, and asserts succeed
2. The router fails to create because the path pattern was invalid

#### Actual Behavior

Errors in `router:match` with
```
radix-router.lua:129: attempt to index local 'routes' (a nil value)
radix-router.lua:197: in function 'match'
```

### PR DESCRIPTION
**Pull request by vm-001**
This PR fixes #53

### CODE REVIEW

File: src/route.lua [hunk 1]
```diff
@@ -17,7 +18,11 @@ function Route.new(route)
 
   for _, path in ipairs(route.paths) do
     if str_byte(path) ~= BYTE_SLASH then
-      return nil, "path must start with /"
+      return nil, "path must starts with /"
+    end
+    local _, pattern_idx = str_find(path, "{%*[^}]*}", 0, false)
```
Comment (Dr-Emann) [inline src/route.lua]: It seems to still work, but I think the `0` should be a `1` here, since it's the index of the character to start at, and lua strings indexes start at 1. 1 and false are the default, though, so this could just be `str_find(path, "{%*[^}]*}")`

**Review by Dr-Emann — APPROVED** [review]

**Comment by vm-001** [comment]
CI fails due to https://github.com/luarocks/luarocks/issues/1797

**Comment by Dr-Emann** [comment]
Looks to be fixed with a new luarocks version
